#!/usr/bin/env python

import cgi
import serial
import time
import sys
import getpass
import fcntl

serialPort = "/dev/ttyACM0"

print "Content-type: text/html"
print ""

command = ""
value = ""

try: 
	fs = cgi.FieldStorage()
	value = fs["value"].value
except: 
	try:
		value = sys.argv[1]
	except:
		print "Error!!!", sys.exc_info()[0]

ser = serial.Serial(serialPort, 2400)

ser.open()
fcntl.flock(ser.fileno(), fcntl.LOCK_EX)

for i in range(0, 4):
	command = "%" + str(i) + "#" + value 
	ser.write(command)

	time.sleep(0.4)

	command = ""

	while ser.inWaiting() > 0:
	  ser.read()

time.sleep(1)

while ser.inWaiting() > 0:
  ser.read()

ser.close()

print '<head><meta HTTP-EQUIV="REFRESH" content="0; url=http://spacecontrol.0x20.be"></head>'

