#!/bin/bash

echo 'Content-type: text/html'
echo ''

OUT=`echo "$QUERY_STRING" | grep -oE "(^|[?&])out=[^&]+" | sed "s/%20/ /g" | cut -f 2 -d "="`
STATUS=`echo "$QUERY_STRING" | grep -oE "(^|[?&])status=[^&]+" | sed "s/%20/ /g" | cut -f 2 -d "="`


if [ "$OUT" == "" ]
then
	OUT=$1
fi

if [ "$STATUS" == "" ]
then
	STATUS=$2
fi

if [ "$OUT" == "all" ]
then
	echo '{"ip" : "172.22.32.60", "devices" : [{"type" : "light", "name" : "2 lamps near couch", "out" : "0"}, {"type" : "light", "name" : "floorlamp 1", "out" : "1"}, {"type" : "light", "name" : "floorlamp 2", "out" : "2"}, {"type" : "light", "name" : "floorlamp 3", "out" : "3"}]}'
else
	./relay $OUT $STATUS &> /dev/null
	echo '{"status" : "'$STATUS'", "out": "'$OUT'"}'
fi
